import React from 'react';

const SeoServices = () => {
    return (
        <div className='h-full'>
            <h2 className='text-black mt-30'>This is seo services page</h2>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Numquam non debitis reprehenderit! Aut delectus voluptas temporibus harum, eaque nihil similique ipsum cum ex in asperiores sit assumenda dignissimos rerum expedita voluptatum tenetur iste deserunt fuga molestiae quis eius. Facilis molestias molestiae unde labore odio animi eius nemo eligendi porro esse asperiores officia sapiente, deserunt magnam itaque commodi nam sit! Quisquam doloribus, rem, ab, blanditiis nostrum ipsa natus ad reiciendis incidunt exercitationem quod placeat dolore dolores! Facilis nulla dolorum corrupti dicta placeat deserunt eos amet, minus quae hic earum molestias soluta obcaecati dolor repellendus dolores esse voluptatibus officiis ex provident natus libero fuga atque nesciunt. Consequatur repellat animi quibusdam vero, rerum exercitationem odit hic laboriosam officia necessitatibus expedita temporibus laborum asperiores accusamus nisi esse dolorem autem enim eaque iusto obcaecati possimus quia corrupti distinctio. Commodi est at rem sapiente quisquam, perspiciatis voluptates officiis harum deleniti doloremque eaque esse. Molestias aliquid dignissimos mollitia totam animi accusantium nobis id aut. Maxime placeat eum, veritatis ea amet molestiae reprehenderit beatae, sed delectus autem neque consequuntur aspernatur voluptatibus harum officia minus vero, quos sunt natus ipsam unde? Dolorum harum, fugiat repellendus in saepe perspiciatis quisquam voluptates voluptatem, ea placeat suscipit. Omnis repellendus esse cupiditate molestias quisquam numquam quasi quam illo, necessitatibus fugit similique sapiente maxime aliquid molestiae minus accusamus quibusdam assumenda! Ullam dolorum repellendus, fuga veritatis esse aut dolor, blanditiis minima molestiae maxime inventore, tempore consequuntur facere aperiam ex aliquid distinctio totam saepe illo est incidunt ducimus odit! Neque unde earum ducimus eos eum aspernatur pariatur blanditiis velit, maxime assumenda laborum quos ex ad ipsum corporis quidem dolorum repellendus quam odit! Soluta dolores harum, cum et ad quam dicta! Ea, iste quas voluptate, reiciendis sed itaque error nemo alias dolore quos illum sapiente necessitatibus rem animi earum culpa, architecto ad fuga eveniet voluptatibus laboriosam blanditiis.</p>
        </div>
    );
};

export default SeoServices;